### ISSUE TITLE
[feat] 첫화면 ->회원가입,로그인 화면으로 이동 기능 구현

### ISSUE THREAD

**Issue by yeriinnn** [SSU-UserInterface/Android-project-kisyuksa#21]
## ISSUE
- 첫화면 ->회원가입,로그인 화면으로 이동 기능 구현

## To-do
- [x] first->로그인 화면으로 전환
- [x] first-> 회원가입 화면으로 전환
- [x] signin액티비티에서 로그인 버튼 클릭 시 바텀네비액티비티 이동
