### ISSUE TITLE
[feat] 회원가입 기능 구현

### ISSUE THREAD

**Issue by yeriinnn** [SSU-UserInterface/Android-project-kisyuksa#25]
## ISSUE
- 회원가입 기능 구현

## To-do
- [x] 회원가입내의 버튼 클릭 기능 구현
- [x] 이메일, 비밀번호 입력 관련 기능 구현
- [x] 회원가입 시 정보 입력 관련 기능 구현
- [x] 회원가입 완료 버튼 클릭 후 로그인 화면 이동시 토스트메시지 띄우기
- [x] 파이어베이스 연결 후 로그인 시 유저 정보 업로드 (파어어베이스auth이용)
- [x] 파이어베이스 스토어에 유저 정보(이름,기숙사호실,닉네임) 저장되는 기능 추가

## 참고사항 및 체크포인트
파이어베이스 연결 후 진행
