### ISSUE TITLE
라운지 구현

### ISSUE THREAD

**Issue by modneyTree** [SSU-UserInterface/Android-project-kisyuksa#40]
## ISSUE
- 라운지 화면 구성

## To-do
- [x] #41
- [x]  헬스 등록증 업로드 및 다운로드(핵심기능)
- [ ] ott 공유 구현(핵싱기능)
- [ ] chat방 구현(핵심기능)
